# Generated by Django 6.0.6 on 2026-07-06 09:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=128)),
                ('localisation', models.CharField(max_length=64)),
                ('capacite', models.PositiveIntegerField()),
            ],
            options={
                'ordering': ['nom', '-capacite'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=64)),
                ('quantite', models.PositiveIntegerField()),
                ('date_expiration', models.DateField()),
                ('etat', models.CharField(choices=[('disponible', 'Disponible'), ('réservé', 'Réservé'), ('périmé', 'Périmé')], default='disponible', max_length=20)),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='ecostock.warehouse')),
            ],
            options={
                'ordering': ['nom', 'date_expiration'],
            },
        ),
    ]
